### ISSUE TITLE
Error when following "The Common Helm Helper Chart" in https://helm.sh/docs/topics/library_charts

### ISSUE THREAD

**Issue by bennythejudge** [helm/helm-www#1208]
Howdy helmers,

1) I was following the tutorial starting from https://helm.sh/docs/topics/library_charts/#
2) at the end instead of doing an `helm install` as suggested by the closing sentence (`It is good to go now, so deploy away!`), I did a `helm lint`.
3) this results in : 

```
==> Linting .
[INFO] Chart.yaml: icon is recommended
[WARNING] templates/deployment.yaml: extensions/v1beta1 Deployment is deprecated in v1.8+, unavailable in v1.16+; use apps/v1 Deployment
[ERROR] templates/deployment.yaml: a Deployment must contain matchLabels or matchExpressions, and "test-release-demo" does not

Error: 1 chart(s) linted, 1 chart(s) failed
```

4) I then executed a 

```
helm template . --output-dir generated
```

which confirmed the `lint` error:

```
head generated/demo/templates/deployment.yaml
---
# Source: demo/templates/deployment.yaml
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  labels:
    app: demo
    chart: demo-0.1.0
    heritage: Helm
    release: RELEASE-NAME
```

5) I am new to `library charts` and to `Common Helm Helper Chart`, but based on the warning at the beginning of the paragraph: 

```
Note: The Common Helm Helper Chart repo on Github is no longer actively maintained, and the repo has been deprecated and archived. 
```

I am wondering if this entire paragraph still makes sense or if it should be removed.
Thanks
