### ISSUE TITLE
weird nesting issue with ServiceAccount.metadata.labels.labels

### ISSUE THREAD

**Issue by tthomaspax8** [helm/helm-www#1349]
So, I'm just following along with the docs, minding my own business when this happens:

```sh
Error: INSTALLATION FAILED: unable to build Kubernetes objects from release manifest: error validating "": error validating data: ValidationError(ServiceAccount.metadata.labels.labels): invalid type for io.k8s.apimachinery.pkg.apis.meta.v1.ObjectMeta.labels: got "map", expected "string"
```

This bit of [the docs] just doesn't work as expected:

```yaml
{{- define "mychart.labels" }}
  labels:
    generator: helm
    date: {{ now | htmlDate }}
{{- end }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Release.Name }}-configmap
  {{- template "mychart.labels" }}
data:
  myvalue: "Hello World"
```

Steps to reproduce

1. `helm create mychart`
2. create a configmap.yaml and drop the above block in there
3. `helm install test ./mychart --dry-run`
4. FAIL, with the above error.

I'm just beginning with this tool but it looks as if `ServiceAccount.metadata.labels.labels` is not quite right. 

```sh
macOS: 12.5.1 (21G83)
helm version --short                                                                                                                                                <aws:default>
v3.9.4+gdbc6d8e
```

But perhaps I'm missing something? 🤔 

[the docs]:https://github.com/helm/helm-www/blob/main/content/en/docs/chart_template_guide/named_templates.md?plain=1#L75-L89
