### ISSUE TITLE
Chart Template Guide: Confusing statement about unnecessary conditional

### ISSUE THREAD

**Issue by windmueller** [helm/helm-www#1697]
The section [Flow Control](https://helm.sh/docs/chart_template_guide/control_structures/) of the Chart Template Guide has this listing:

```yaml
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Release.Name }}-configmap
data:
  myvalue: "Hello World"
  {{- with .Values.favorite }}
  drink: {{ .drink | default "tea" | quote }}
  food: {{ .food | upper | quote }}
  {{- end }}
```

In the next paragraph it states:

> Note that we removed the `if` conditional from the previous exercise because it is now unnecessary - the block after `with` only executes if the value of `PIPELINE` is not empty.

However, the now omitted conditional was:

```
  {{- if eq .Values.favorite.drink "coffee" }}
  mug: "true"
  {{- end }}
```

That statement does not check if the value is empty but if `.drink` matches "coffee".

Has the example been changed without modifying the text or am I missing something here?

In my opinion the example should now be:

```yaml
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Release.Name }}-configmap
data:
  myvalue: "Hello World"
  {{- with .Values.favorite }}
  drink: {{ .drink | default "tea" | quote }}
  food: {{ .food | upper | quote }}
  {{- if eq .drink "coffee" }}
  mug: true
  {{- end }}
  {{- end }}
```
